[package]
name = "spirv-builder-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo-gpu = { path = "../cargo-gpu" }
env_home = "0.1.0"
env_logger = "0.10"
log = "0.4"
serde = "1.0.214"
serde_json = "1.0.132"
spirv-builder = { path = "../spirv-builder-dummy" }
toml = "0.8.19"